steps:

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/sinhala-transcriber/sinhala-transcriber'
  - '.'

images:

- 'europe-west1-docker.pkg.dev/$PROJECT_ID/sinhala-transcriber/sinhala-transcriber'

options:
  logging: CLOUD_LOGGING_ONLY
